remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme
# theme: jekyll-theme-dinky
title: Octocat's homepage
description: Bookmark this to keep an eye on my project updates!
markdown: GFM
show_downloads: false
